#!/usr/bin/env bash
set -euo pipefail
APP_NAME="loophole-cli"
APP_EXEC="loophole"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
ORANGE='\033[38;2;255;140;0m'
NC='\033[0m' # No Color

requested_version=${VERSION:-}

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)

if [[ "$os" == "darwin" ]]; then
    os="darwin"
elif [[ "$os" == "linux" ]]; then
    os="linux"
elif [[ "$os" == "mingw"* || "$os" == "cygwin"* || "$os" == "win"* ]]; then
    os="windows"
fi

if [[ "$arch" == "x86_64" ]]; then
  arch="amd64"
elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
  arch="arm64"
fi

filename="${APP_NAME}-${os}-${arch}"
if [[ "$os" == "windows" ]]; then
    filename="${filename}.exe"
fi

INSTALL_DIR=$HOME/.loophole/bin
mkdir -p "$INSTALL_DIR"

if [ -z "$requested_version" ]; then
    latest_release_json=$(curl -s https://api.github.com/repos/loophole-ai/loophole-cli/releases/latest)
    specific_version=$(echo "$latest_release_json" | grep -oP '"tag_name": "\K[^"]+' | sed 's/^v//')
    url="https://github.com/loophole-ai/loophole-cli/releases/latest/download/$filename"
else
    url="https://github.com/loophole-ai/loophole-cli/releases/download/v${requested_version}/$filename"
    specific_version=$requested_version
fi


print_message() {
    local level=$1
    local message=$2
    local color=""

    case $level in
        info) color="${GREEN}" ;;
        warning) color="${YELLOW}" ;;
        error) color="${RED}" ;;
    esac

    echo -e "${color}${message}${NC}"
}

check_version() {
    if command -v loophole >/dev/null 2>&1; then
        loophole_path=$(which loophole)


        ## TODO: check if version is installed
        # installed_version=$(loophole version)
        installed_version="0.0.1"
        installed_version=$(echo $installed_version | awk '{print $2}')

        if [[ "$installed_version" != "$specific_version" ]]; then
            print_message info "Installed version: ${YELLOW}$installed_version."
        else
            print_message info "Version ${YELLOW}$specific_version${GREEN} already installed"
            exit 0
        fi
    fi
}

download_and_install() {
    print_message info "Downloading ${ORANGE}${APP_EXEC} ${GREEN}version: ${YELLOW}$specific_version ${GREEN}..."
    mkdir -p loopholetmp && cd loopholetmp
    curl -# -L -O $url
    
    # If it's a binary with .exe, rename it correctly
    if [[ -f "${filename}" ]]; then
        chmod +x "${filename}"
        mv "${filename}" "$INSTALL_DIR/${APP_EXEC}"
    elif [[ -f "${filename}.exe" ]]; then
        mv "${filename}.exe" "$INSTALL_DIR/${APP_EXEC}.exe"
    fi
    
    cd .. && rm -rf loopholetmp 
}

check_version
download_and_install


add_to_path() {
    local config_file=$1
    local command=$2

    if [[ -w $config_file ]]; then
        echo -e "\n# loophole" >> "$config_file"
        echo "$command" >> "$config_file"
        print_message info "Successfully added ${ORANGE}loophole ${GREEN}to \$PATH in $config_file"
    else
        print_message warning "Manually add the directory to $config_file (or similar):"
        print_message info "  $command"
    fi
}

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

current_shell=$(basename "$SHELL")
case $current_shell in
    fish)
        config_files="$HOME/.config/fish/config.fish"
    ;;
    zsh)
        config_files="$HOME/.zshrc $HOME/.zshenv $XDG_CONFIG_HOME/zsh/.zshrc $XDG_CONFIG_HOME/zsh/.zshenv"
    ;;
    bash)
        config_files="$HOME/.bashrc $HOME/.bash_profile $HOME/.profile $XDG_CONFIG_HOME/bash/.bashrc $XDG_CONFIG_HOME/bash/.bash_profile"
    ;;
    ash)
        config_files="$HOME/.ashrc $HOME/.profile /etc/profile"
    ;;
    sh)
        config_files="$HOME/.ashrc $HOME/.profile /etc/profile"
    ;;
    *)
        # Default case if none of the above matches
        config_files="$HOME/.bashrc $HOME/.bash_profile $XDG_CONFIG_HOME/bash/.bashrc $XDG_CONFIG_HOME/bash/.bash_profile"
    ;;
esac

config_file=""
for file in $config_files; do
    if [[ -f $file ]]; then
        config_file=$file
        break
    fi
done

if [[ -z $config_file ]]; then
    print_message error "No config file found for $current_shell. Checked files: ${config_files[@]}"
    exit 1
fi

if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    case $current_shell in
        fish)
            add_to_path "$config_file" "fish_add_path $INSTALL_DIR"
        ;;
        zsh)
            add_to_path "$config_file" "export PATH=$INSTALL_DIR:\$PATH"
        ;;
        bash)
            add_to_path "$config_file" "export PATH=$INSTALL_DIR:\$PATH"
        ;;
        ash)
            add_to_path "$config_file" "export PATH=$INSTALL_DIR:\$PATH"
        ;;
        sh)
            add_to_path "$config_file" "export PATH=$INSTALL_DIR:\$PATH"
        ;;
        *)
            print_message warning "Manually add the directory to $config_file (or similar):"
            print_message info "  export PATH=$INSTALL_DIR:\$PATH"
        ;;
    esac
fi

if [ -n "${GITHUB_ACTIONS-}" ] && [ "${GITHUB_ACTIONS}" == "true" ]; then
    echo "$INSTALL_DIR" >> $GITHUB_PATH
    print_message info "Added $INSTALL_DIR to \$GITHUB_PATH"
fi

